name: ROS Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
        ros-distro: [kinetic]

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ros-tooling/setup-ros@0.0.26
    - uses: ros-tooling/action-ros2-lint@0.0.6
      with:
        target-ros1-distro: kinetic
        package-name: i3dr_deimos
